name: Build Mac (Universal)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # BUILD PER MAC APPLE SILICON (M1/M2/M3)
  build-mac-arm64:
    name: Build Mac Apple Silicon
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install -r backend/requirements.txt
          pip install pyinstaller
      - run: python -m PyInstaller --clean --noconfirm --onefile --name api api.py --distpath ../backend/dist --workpath ../backend/build
        working-directory: backend
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run dist -- --mac --arm64
      - uses: actions/upload-artifact@v4
        with:
          name: Mac-AppleSilicon-App
          path: dist/*.dmg

  # BUILD PER MAC INTEL (x64)
  build-mac-x64:
    name: Build Mac Intel
    runs-on: macos-12  # Usiamo macos-12 (Intel) per stabilit√†
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install -r backend/requirements.txt
          pip install pyinstaller
      - run: python -m PyInstaller --clean --noconfirm --onefile --name api api.py --distpath ../backend/dist --workpath ../backend/build
        working-directory: backend
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run dist -- --mac --x64
      - uses: actions/upload-artifact@v4
        with:
          name: Mac-Intel-App
          path: dist/*.dmg